# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrUfewoI83xAhQy426LR4zyk7pOFPRav
"""

materias = ["Matemática","Inglês","Espanhol", "Históra","SC","ATE","BIL","FIL","FIS","GEO","ED","POR","QUI"]

#mostra a materia selecionada
for x in materias:
  print(f"{x}")

#pede as notas do primeiro e segundo trimestre
  n1 = float(input("Digite a primeira nota: "))
  n2 = float(input("Digite a segunda nota: "))

#calcula quanto falta para alcançar a nota final
  print("----------------------")

  falta = 18 - (n1 + n2)

#mostra o resultado
  print(f"Será necessario {falta} ponto(s) no proximo trimestre")
  print("----------------------")
