# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrUfewoI83xAhQy426LR4zyk7pOFPRav
"""

#aqui as variavés estão recebendo as informações

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")

#aqui o ano está recebendo o ano atual
ano = 2024

idade = int(idade)
#aqui é feito a soma para calcular o ano que a pessoa fará 100 anos
soma = 100 - idade + ano

print(f"Parabéns,Você fará 100 anos em {soma}!!")

print(4 * " teste ")

numero = int(input("Digite o numero: "))


soma = numero % 2

print(f"O restante é: {soma}")

if soma == 0:
  print("O numero é par")
else:
  print("O numero é impar")



lista = [1,1,2,3,5,8,13,21,34]

numero = int(input("Digite o numero: "))

for x in lista:
  if x <= numero:
    print(x, end=" ")

materias = ["Matemática","Inglês","Espanhol", "Históra","SC","ATE","BIL","FIL","FIS","GEO","ED","POR","QUI"]

#mostra quais são as materia disponiveis
for x in materias:
  print(f"{x}")

#retorna a materia selecionada
  n1 = float(input("Digite a primeira nota: "))
  n2 = float(input("Digite a segunda nota: "))

#calcula quanto falta para alcançar a nota final
  print("----------------------")

  falta = 18 - (n1 + n2)

#mostra o resultado
  print(f"Será necessario {falta} ponto(s) no proximo trimestre")
  print("----------------------")